version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-task-manager
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: .
    container_name: task-manager-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres.ydioclfnezasxtlrilmn
      SPRING_DATASOURCE_PASSWORD: task_manager_db

      SPRING_RABBITMQ_HOST: rabbitmq-task-manager
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest