spring.application.name=task-manager-api

# Server Context Path
server.servlet.context-path=/api

# RabbitMQ
spring.rabbitmq.host=rabbitmq-task-manager
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres-task-manager:5432/task_manager_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect